[package]
name = "example-host"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.3.19", features = ["derive"] }
wasmtime = { version = "18", features = ["component-model"] }
wasmtime-wasi = "18"
anyhow = "1.0.72"
